// <auto-generated />
using System;
using MADAI_BACKEND.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MADAI_BACKEND.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250515090436_AddMedicalHistoryEntry1")]
    partial class AddMedicalHistoryEntry1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MADAI_BACKEND.Models.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NextSteps")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedConditions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("SymptomEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SymptomEntryId")
                        .IsUnique();

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("MADAI_BACKEND.Models.MedicalHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MedicalHistoryEntries");
                });

            modelBuilder.Entity("MADAI_BACKEND.Models.SymptomEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SymptomsText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SymptomEntries");
                });

            modelBuilder.Entity("MADAI_BACKEND.Models.AnalysisResult", b =>
                {
                    b.HasOne("MADAI_BACKEND.Models.SymptomEntry", "SymptomEntry")
                        .WithOne("AnalysisResult")
                        .HasForeignKey("MADAI_BACKEND.Models.AnalysisResult", "SymptomEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SymptomEntry");
                });

            modelBuilder.Entity("MADAI_BACKEND.Models.SymptomEntry", b =>
                {
                    b.Navigation("AnalysisResult");
                });
#pragma warning restore 612, 618
        }
    }
}
